//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("dbModel", "FK_firma_adresa", "adresa", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(bcpp.Models.adresa), "firma", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(bcpp.Models.firma), true)]
[assembly: EdmRelationshipAttribute("dbModel", "FK_uzivatel_adresa", "adresa", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(bcpp.Models.adresa), "uzivatel", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(bcpp.Models.uzivatel), true)]
[assembly: EdmRelationshipAttribute("dbModel", "FK_akcie_firma", "firma", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(bcpp.Models.firma), "akcie", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(bcpp.Models.akcie), true)]
[assembly: EdmRelationshipAttribute("dbModel", "FK_historie_akcie_akcie", "akcie", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(bcpp.Models.akcie), "historie_akcie", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(bcpp.Models.historie_akcie), true)]
[assembly: EdmRelationshipAttribute("dbModel", "FK_portfolio_akcie", "akcie", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(bcpp.Models.akcie), "portfolio", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(bcpp.Models.portfolio), true)]
[assembly: EdmRelationshipAttribute("dbModel", "FK_sledovane_akcie", "akcie", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(bcpp.Models.akcie), "sledovane", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(bcpp.Models.sledovane), true)]
[assembly: EdmRelationshipAttribute("dbModel", "FK_historie_poukazek_pokl_poukazky", "pokl_poukazky", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(bcpp.Models.pokl_poukazky), "historie_poukazek", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(bcpp.Models.historie_poukazek), true)]
[assembly: EdmRelationshipAttribute("dbModel", "FK_portfolio_uzivatel", "uzivatel", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(bcpp.Models.uzivatel), "portfolio", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(bcpp.Models.portfolio), true)]
[assembly: EdmRelationshipAttribute("dbModel", "FK_sledovane_uzivatel", "uzivatel", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(bcpp.Models.uzivatel), "sledovane", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(bcpp.Models.sledovane), true)]

#endregion

namespace bcpp.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbEntities object using the connection string found in the 'dbEntities' section of the application configuration file.
        /// </summary>
        public dbEntities() : base("name=dbEntities", "dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbEntities object.
        /// </summary>
        public dbEntities(string connectionString) : base(connectionString, "dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbEntities object.
        /// </summary>
        public dbEntities(EntityConnection connection) : base(connection, "dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<adresa> adresa
        {
            get
            {
                if ((_adresa == null))
                {
                    _adresa = base.CreateObjectSet<adresa>("adresa");
                }
                return _adresa;
            }
        }
        private ObjectSet<adresa> _adresa;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<akcie> akcie
        {
            get
            {
                if ((_akcie == null))
                {
                    _akcie = base.CreateObjectSet<akcie>("akcie");
                }
                return _akcie;
            }
        }
        private ObjectSet<akcie> _akcie;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<firma> firma
        {
            get
            {
                if ((_firma == null))
                {
                    _firma = base.CreateObjectSet<firma>("firma");
                }
                return _firma;
            }
        }
        private ObjectSet<firma> _firma;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<historie_akcie> historie_akcie
        {
            get
            {
                if ((_historie_akcie == null))
                {
                    _historie_akcie = base.CreateObjectSet<historie_akcie>("historie_akcie");
                }
                return _historie_akcie;
            }
        }
        private ObjectSet<historie_akcie> _historie_akcie;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<historie_poukazek> historie_poukazek
        {
            get
            {
                if ((_historie_poukazek == null))
                {
                    _historie_poukazek = base.CreateObjectSet<historie_poukazek>("historie_poukazek");
                }
                return _historie_poukazek;
            }
        }
        private ObjectSet<historie_poukazek> _historie_poukazek;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<index_PX> index_PX
        {
            get
            {
                if ((_index_PX == null))
                {
                    _index_PX = base.CreateObjectSet<index_PX>("index_PX");
                }
                return _index_PX;
            }
        }
        private ObjectSet<index_PX> _index_PX;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<pokl_poukazky> pokl_poukazky
        {
            get
            {
                if ((_pokl_poukazky == null))
                {
                    _pokl_poukazky = base.CreateObjectSet<pokl_poukazky>("pokl_poukazky");
                }
                return _pokl_poukazky;
            }
        }
        private ObjectSet<pokl_poukazky> _pokl_poukazky;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<portfolio> portfolio
        {
            get
            {
                if ((_portfolio == null))
                {
                    _portfolio = base.CreateObjectSet<portfolio>("portfolio");
                }
                return _portfolio;
            }
        }
        private ObjectSet<portfolio> _portfolio;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sledovane> sledovane
        {
            get
            {
                if ((_sledovane == null))
                {
                    _sledovane = base.CreateObjectSet<sledovane>("sledovane");
                }
                return _sledovane;
            }
        }
        private ObjectSet<sledovane> _sledovane;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<uzivatel> uzivatel
        {
            get
            {
                if ((_uzivatel == null))
                {
                    _uzivatel = base.CreateObjectSet<uzivatel>("uzivatel");
                }
                return _uzivatel;
            }
        }
        private ObjectSet<uzivatel> _uzivatel;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the adresa EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToadresa(adresa adresa)
        {
            base.AddObject("adresa", adresa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the akcie EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToakcie(akcie akcie)
        {
            base.AddObject("akcie", akcie);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the firma EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofirma(firma firma)
        {
            base.AddObject("firma", firma);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the historie_akcie EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohistorie_akcie(historie_akcie historie_akcie)
        {
            base.AddObject("historie_akcie", historie_akcie);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the historie_poukazek EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohistorie_poukazek(historie_poukazek historie_poukazek)
        {
            base.AddObject("historie_poukazek", historie_poukazek);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the index_PX EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToindex_PX(index_PX index_PX)
        {
            base.AddObject("index_PX", index_PX);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the pokl_poukazky EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopokl_poukazky(pokl_poukazky pokl_poukazky)
        {
            base.AddObject("pokl_poukazky", pokl_poukazky);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the portfolio EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToportfolio(portfolio portfolio)
        {
            base.AddObject("portfolio", portfolio);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sledovane EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosledovane(sledovane sledovane)
        {
            base.AddObject("sledovane", sledovane);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the uzivatel EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouzivatel(uzivatel uzivatel)
        {
            base.AddObject("uzivatel", uzivatel);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iD_Akcie">No Metadata Documentation available.</param>
        public ObjectResult<Nullable<global::System.Double>> Lin_reg(Nullable<global::System.Int32> iD_Akcie)
        {
            ObjectParameter iD_AkcieParameter;
            if (iD_Akcie.HasValue)
            {
                iD_AkcieParameter = new ObjectParameter("ID_Akcie", iD_Akcie);
            }
            else
            {
                iD_AkcieParameter = new ObjectParameter("ID_Akcie", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Double>>("Lin_reg", iD_AkcieParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="adresa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class adresa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new adresa object.
        /// </summary>
        /// <param name="adresa_id">Initial value of the adresa_id property.</param>
        /// <param name="mesto">Initial value of the mesto property.</param>
        /// <param name="ulice">Initial value of the ulice property.</param>
        /// <param name="email">Initial value of the email property.</param>
        public static adresa Createadresa(global::System.Int32 adresa_id, global::System.String mesto, global::System.String ulice, global::System.String email)
        {
            adresa adresa = new adresa();
            adresa.adresa_id = adresa_id;
            adresa.mesto = mesto;
            adresa.ulice = ulice;
            adresa.email = email;
            return adresa;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 adresa_id
        {
            get
            {
                return _adresa_id;
            }
            set
            {
                if (_adresa_id != value)
                {
                    Onadresa_idChanging(value);
                    ReportPropertyChanging("adresa_id");
                    _adresa_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("adresa_id");
                    Onadresa_idChanged();
                }
            }
        }
        private global::System.Int32 _adresa_id;
        partial void Onadresa_idChanging(global::System.Int32 value);
        partial void Onadresa_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mesto
        {
            get
            {
                return _mesto;
            }
            set
            {
                OnmestoChanging(value);
                ReportPropertyChanging("mesto");
                _mesto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mesto");
                OnmestoChanged();
            }
        }
        private global::System.String _mesto;
        partial void OnmestoChanging(global::System.String value);
        partial void OnmestoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ulice
        {
            get
            {
                return _ulice;
            }
            set
            {
                OnuliceChanging(value);
                ReportPropertyChanging("ulice");
                _ulice = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ulice");
                OnuliceChanged();
            }
        }
        private global::System.String _ulice;
        partial void OnuliceChanging(global::System.String value);
        partial void OnuliceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PSC
        {
            get
            {
                return _PSC;
            }
            set
            {
                OnPSCChanging(value);
                ReportPropertyChanging("PSC");
                _PSC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PSC");
                OnPSCChanged();
            }
        }
        private global::System.String _PSC;
        partial void OnPSCChanging(global::System.String value);
        partial void OnPSCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefon
        {
            get
            {
                return _telefon;
            }
            set
            {
                OntelefonChanging(value);
                ReportPropertyChanging("telefon");
                _telefon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telefon");
                OntelefonChanged();
            }
        }
        private global::System.String _telefon;
        partial void OntelefonChanging(global::System.String value);
        partial void OntelefonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_firma_adresa", "firma")]
        public EntityCollection<firma> firma
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<firma>("dbModel.FK_firma_adresa", "firma");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<firma>("dbModel.FK_firma_adresa", "firma", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_uzivatel_adresa", "uzivatel")]
        public EntityCollection<uzivatel> uzivatel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<uzivatel>("dbModel.FK_uzivatel_adresa", "uzivatel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<uzivatel>("dbModel.FK_uzivatel_adresa", "uzivatel", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="akcie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class akcie : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new akcie object.
        /// </summary>
        /// <param name="akcie_id">Initial value of the akcie_id property.</param>
        /// <param name="firma_id">Initial value of the firma_id property.</param>
        /// <param name="nazev">Initial value of the nazev property.</param>
        /// <param name="zkratka">Initial value of the zkratka property.</param>
        public static akcie Createakcie(global::System.Int32 akcie_id, global::System.Int32 firma_id, global::System.String nazev, global::System.String zkratka)
        {
            akcie akcie = new akcie();
            akcie.akcie_id = akcie_id;
            akcie.firma_id = firma_id;
            akcie.nazev = nazev;
            akcie.zkratka = zkratka;
            return akcie;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 akcie_id
        {
            get
            {
                return _akcie_id;
            }
            set
            {
                if (_akcie_id != value)
                {
                    Onakcie_idChanging(value);
                    ReportPropertyChanging("akcie_id");
                    _akcie_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("akcie_id");
                    Onakcie_idChanged();
                }
            }
        }
        private global::System.Int32 _akcie_id;
        partial void Onakcie_idChanging(global::System.Int32 value);
        partial void Onakcie_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 firma_id
        {
            get
            {
                return _firma_id;
            }
            set
            {
                Onfirma_idChanging(value);
                ReportPropertyChanging("firma_id");
                _firma_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("firma_id");
                Onfirma_idChanged();
            }
        }
        private global::System.Int32 _firma_id;
        partial void Onfirma_idChanging(global::System.Int32 value);
        partial void Onfirma_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nazev
        {
            get
            {
                return _nazev;
            }
            set
            {
                OnnazevChanging(value);
                ReportPropertyChanging("nazev");
                _nazev = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nazev");
                OnnazevChanged();
            }
        }
        private global::System.String _nazev;
        partial void OnnazevChanging(global::System.String value);
        partial void OnnazevChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String zkratka
        {
            get
            {
                return _zkratka;
            }
            set
            {
                OnzkratkaChanging(value);
                ReportPropertyChanging("zkratka");
                _zkratka = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("zkratka");
                OnzkratkaChanged();
            }
        }
        private global::System.String _zkratka;
        partial void OnzkratkaChanging(global::System.String value);
        partial void OnzkratkaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_akcie_firma", "firma")]
        public firma firma
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<firma>("dbModel.FK_akcie_firma", "firma").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<firma>("dbModel.FK_akcie_firma", "firma").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<firma> firmaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<firma>("dbModel.FK_akcie_firma", "firma");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<firma>("dbModel.FK_akcie_firma", "firma", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_historie_akcie_akcie", "historie_akcie")]
        public EntityCollection<historie_akcie> historie_akcie
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<historie_akcie>("dbModel.FK_historie_akcie_akcie", "historie_akcie");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<historie_akcie>("dbModel.FK_historie_akcie_akcie", "historie_akcie", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_portfolio_akcie", "portfolio")]
        public EntityCollection<portfolio> portfolio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<portfolio>("dbModel.FK_portfolio_akcie", "portfolio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<portfolio>("dbModel.FK_portfolio_akcie", "portfolio", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_sledovane_akcie", "sledovane")]
        public EntityCollection<sledovane> sledovane
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<sledovane>("dbModel.FK_sledovane_akcie", "sledovane");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<sledovane>("dbModel.FK_sledovane_akcie", "sledovane", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="firma")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class firma : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new firma object.
        /// </summary>
        /// <param name="firma_id">Initial value of the firma_id property.</param>
        /// <param name="adresa_id">Initial value of the adresa_id property.</param>
        /// <param name="nazev">Initial value of the nazev property.</param>
        public static firma Createfirma(global::System.Int32 firma_id, global::System.Int32 adresa_id, global::System.String nazev)
        {
            firma firma = new firma();
            firma.firma_id = firma_id;
            firma.adresa_id = adresa_id;
            firma.nazev = nazev;
            return firma;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 firma_id
        {
            get
            {
                return _firma_id;
            }
            set
            {
                if (_firma_id != value)
                {
                    Onfirma_idChanging(value);
                    ReportPropertyChanging("firma_id");
                    _firma_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("firma_id");
                    Onfirma_idChanged();
                }
            }
        }
        private global::System.Int32 _firma_id;
        partial void Onfirma_idChanging(global::System.Int32 value);
        partial void Onfirma_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 adresa_id
        {
            get
            {
                return _adresa_id;
            }
            set
            {
                Onadresa_idChanging(value);
                ReportPropertyChanging("adresa_id");
                _adresa_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("adresa_id");
                Onadresa_idChanged();
            }
        }
        private global::System.Int32 _adresa_id;
        partial void Onadresa_idChanging(global::System.Int32 value);
        partial void Onadresa_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nazev
        {
            get
            {
                return _nazev;
            }
            set
            {
                OnnazevChanging(value);
                ReportPropertyChanging("nazev");
                _nazev = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nazev");
                OnnazevChanged();
            }
        }
        private global::System.String _nazev;
        partial void OnnazevChanging(global::System.String value);
        partial void OnnazevChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ICO
        {
            get
            {
                return _ICO;
            }
            set
            {
                OnICOChanging(value);
                ReportPropertyChanging("ICO");
                _ICO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ICO");
                OnICOChanged();
            }
        }
        private global::System.String _ICO;
        partial void OnICOChanging(global::System.String value);
        partial void OnICOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DIC
        {
            get
            {
                return _DIC;
            }
            set
            {
                OnDICChanging(value);
                ReportPropertyChanging("DIC");
                _DIC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DIC");
                OnDICChanged();
            }
        }
        private global::System.String _DIC;
        partial void OnDICChanging(global::System.String value);
        partial void OnDICChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_firma_adresa", "adresa")]
        public adresa adresa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<adresa>("dbModel.FK_firma_adresa", "adresa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<adresa>("dbModel.FK_firma_adresa", "adresa").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<adresa> adresaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<adresa>("dbModel.FK_firma_adresa", "adresa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<adresa>("dbModel.FK_firma_adresa", "adresa", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_akcie_firma", "akcie")]
        public EntityCollection<akcie> akcie
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<akcie>("dbModel.FK_akcie_firma", "akcie");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<akcie>("dbModel.FK_akcie_firma", "akcie", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="historie_akcie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class historie_akcie : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new historie_akcie object.
        /// </summary>
        /// <param name="historie_id">Initial value of the historie_id property.</param>
        /// <param name="datum">Initial value of the datum property.</param>
        /// <param name="akcie_id">Initial value of the akcie_id property.</param>
        /// <param name="cena_prodej">Initial value of the cena_prodej property.</param>
        /// <param name="cena_nakup">Initial value of the cena_nakup property.</param>
        public static historie_akcie Createhistorie_akcie(global::System.Int32 historie_id, global::System.DateTime datum, global::System.Int32 akcie_id, global::System.Single cena_prodej, global::System.Single cena_nakup)
        {
            historie_akcie historie_akcie = new historie_akcie();
            historie_akcie.historie_id = historie_id;
            historie_akcie.datum = datum;
            historie_akcie.akcie_id = akcie_id;
            historie_akcie.cena_prodej = cena_prodej;
            historie_akcie.cena_nakup = cena_nakup;
            return historie_akcie;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 historie_id
        {
            get
            {
                return _historie_id;
            }
            set
            {
                if (_historie_id != value)
                {
                    Onhistorie_idChanging(value);
                    ReportPropertyChanging("historie_id");
                    _historie_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("historie_id");
                    Onhistorie_idChanged();
                }
            }
        }
        private global::System.Int32 _historie_id;
        partial void Onhistorie_idChanging(global::System.Int32 value);
        partial void Onhistorie_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime datum
        {
            get
            {
                return _datum;
            }
            set
            {
                if (_datum != value)
                {
                    OndatumChanging(value);
                    ReportPropertyChanging("datum");
                    _datum = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("datum");
                    OndatumChanged();
                }
            }
        }
        private global::System.DateTime _datum;
        partial void OndatumChanging(global::System.DateTime value);
        partial void OndatumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 akcie_id
        {
            get
            {
                return _akcie_id;
            }
            set
            {
                Onakcie_idChanging(value);
                ReportPropertyChanging("akcie_id");
                _akcie_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("akcie_id");
                Onakcie_idChanged();
            }
        }
        private global::System.Int32 _akcie_id;
        partial void Onakcie_idChanging(global::System.Int32 value);
        partial void Onakcie_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single cena_prodej
        {
            get
            {
                return _cena_prodej;
            }
            set
            {
                Oncena_prodejChanging(value);
                ReportPropertyChanging("cena_prodej");
                _cena_prodej = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cena_prodej");
                Oncena_prodejChanged();
            }
        }
        private global::System.Single _cena_prodej;
        partial void Oncena_prodejChanging(global::System.Single value);
        partial void Oncena_prodejChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single cena_nakup
        {
            get
            {
                return _cena_nakup;
            }
            set
            {
                Oncena_nakupChanging(value);
                ReportPropertyChanging("cena_nakup");
                _cena_nakup = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cena_nakup");
                Oncena_nakupChanged();
            }
        }
        private global::System.Single _cena_nakup;
        partial void Oncena_nakupChanging(global::System.Single value);
        partial void Oncena_nakupChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_historie_akcie_akcie", "akcie")]
        public akcie akcie
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akcie>("dbModel.FK_historie_akcie_akcie", "akcie").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akcie>("dbModel.FK_historie_akcie_akcie", "akcie").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<akcie> akcieReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akcie>("dbModel.FK_historie_akcie_akcie", "akcie");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<akcie>("dbModel.FK_historie_akcie_akcie", "akcie", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="historie_poukazek")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class historie_poukazek : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new historie_poukazek object.
        /// </summary>
        /// <param name="poukazka_id">Initial value of the poukazka_id property.</param>
        /// <param name="datum">Initial value of the datum property.</param>
        /// <param name="urok">Initial value of the urok property.</param>
        public static historie_poukazek Createhistorie_poukazek(global::System.Int32 poukazka_id, global::System.DateTime datum, global::System.Single urok)
        {
            historie_poukazek historie_poukazek = new historie_poukazek();
            historie_poukazek.poukazka_id = poukazka_id;
            historie_poukazek.datum = datum;
            historie_poukazek.urok = urok;
            return historie_poukazek;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 poukazka_id
        {
            get
            {
                return _poukazka_id;
            }
            set
            {
                if (_poukazka_id != value)
                {
                    Onpoukazka_idChanging(value);
                    ReportPropertyChanging("poukazka_id");
                    _poukazka_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("poukazka_id");
                    Onpoukazka_idChanged();
                }
            }
        }
        private global::System.Int32 _poukazka_id;
        partial void Onpoukazka_idChanging(global::System.Int32 value);
        partial void Onpoukazka_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime datum
        {
            get
            {
                return _datum;
            }
            set
            {
                if (_datum != value)
                {
                    OndatumChanging(value);
                    ReportPropertyChanging("datum");
                    _datum = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("datum");
                    OndatumChanged();
                }
            }
        }
        private global::System.DateTime _datum;
        partial void OndatumChanging(global::System.DateTime value);
        partial void OndatumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single urok
        {
            get
            {
                return _urok;
            }
            set
            {
                OnurokChanging(value);
                ReportPropertyChanging("urok");
                _urok = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("urok");
                OnurokChanged();
            }
        }
        private global::System.Single _urok;
        partial void OnurokChanging(global::System.Single value);
        partial void OnurokChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_historie_poukazek_pokl_poukazky", "pokl_poukazky")]
        public pokl_poukazky pokl_poukazky
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<pokl_poukazky>("dbModel.FK_historie_poukazek_pokl_poukazky", "pokl_poukazky").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<pokl_poukazky>("dbModel.FK_historie_poukazek_pokl_poukazky", "pokl_poukazky").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<pokl_poukazky> pokl_poukazkyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<pokl_poukazky>("dbModel.FK_historie_poukazek_pokl_poukazky", "pokl_poukazky");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<pokl_poukazky>("dbModel.FK_historie_poukazek_pokl_poukazky", "pokl_poukazky", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="index_PX")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class index_PX : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new index_PX object.
        /// </summary>
        /// <param name="datum">Initial value of the datum property.</param>
        /// <param name="hodnota">Initial value of the hodnota property.</param>
        public static index_PX Createindex_PX(global::System.DateTime datum, global::System.Single hodnota)
        {
            index_PX index_PX = new index_PX();
            index_PX.datum = datum;
            index_PX.hodnota = hodnota;
            return index_PX;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime datum
        {
            get
            {
                return _datum;
            }
            set
            {
                if (_datum != value)
                {
                    OndatumChanging(value);
                    ReportPropertyChanging("datum");
                    _datum = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("datum");
                    OndatumChanged();
                }
            }
        }
        private global::System.DateTime _datum;
        partial void OndatumChanging(global::System.DateTime value);
        partial void OndatumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single hodnota
        {
            get
            {
                return _hodnota;
            }
            set
            {
                OnhodnotaChanging(value);
                ReportPropertyChanging("hodnota");
                _hodnota = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hodnota");
                OnhodnotaChanged();
            }
        }
        private global::System.Single _hodnota;
        partial void OnhodnotaChanging(global::System.Single value);
        partial void OnhodnotaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="pokl_poukazky")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class pokl_poukazky : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new pokl_poukazky object.
        /// </summary>
        /// <param name="poukazka_id">Initial value of the poukazka_id property.</param>
        /// <param name="nazev">Initial value of the nazev property.</param>
        /// <param name="zkratka">Initial value of the zkratka property.</param>
        public static pokl_poukazky Createpokl_poukazky(global::System.Int32 poukazka_id, global::System.String nazev, global::System.String zkratka)
        {
            pokl_poukazky pokl_poukazky = new pokl_poukazky();
            pokl_poukazky.poukazka_id = poukazka_id;
            pokl_poukazky.nazev = nazev;
            pokl_poukazky.zkratka = zkratka;
            return pokl_poukazky;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 poukazka_id
        {
            get
            {
                return _poukazka_id;
            }
            set
            {
                if (_poukazka_id != value)
                {
                    Onpoukazka_idChanging(value);
                    ReportPropertyChanging("poukazka_id");
                    _poukazka_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("poukazka_id");
                    Onpoukazka_idChanged();
                }
            }
        }
        private global::System.Int32 _poukazka_id;
        partial void Onpoukazka_idChanging(global::System.Int32 value);
        partial void Onpoukazka_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nazev
        {
            get
            {
                return _nazev;
            }
            set
            {
                OnnazevChanging(value);
                ReportPropertyChanging("nazev");
                _nazev = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nazev");
                OnnazevChanged();
            }
        }
        private global::System.String _nazev;
        partial void OnnazevChanging(global::System.String value);
        partial void OnnazevChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String zkratka
        {
            get
            {
                return _zkratka;
            }
            set
            {
                OnzkratkaChanging(value);
                ReportPropertyChanging("zkratka");
                _zkratka = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("zkratka");
                OnzkratkaChanged();
            }
        }
        private global::System.String _zkratka;
        partial void OnzkratkaChanging(global::System.String value);
        partial void OnzkratkaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_historie_poukazek_pokl_poukazky", "historie_poukazek")]
        public EntityCollection<historie_poukazek> historie_poukazek
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<historie_poukazek>("dbModel.FK_historie_poukazek_pokl_poukazky", "historie_poukazek");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<historie_poukazek>("dbModel.FK_historie_poukazek_pokl_poukazky", "historie_poukazek", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="portfolio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class portfolio : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new portfolio object.
        /// </summary>
        /// <param name="portfolio_id">Initial value of the portfolio_id property.</param>
        /// <param name="uzivatel_id">Initial value of the uzivatel_id property.</param>
        /// <param name="akcie_id">Initial value of the akcie_id property.</param>
        /// <param name="pocet">Initial value of the pocet property.</param>
        /// <param name="cena">Initial value of the cena property.</param>
        /// <param name="nakup">Initial value of the nakup property.</param>
        /// <param name="datum_zmeny">Initial value of the datum_zmeny property.</param>
        public static portfolio Createportfolio(global::System.Int32 portfolio_id, global::System.Int32 uzivatel_id, global::System.Int32 akcie_id, global::System.Int32 pocet, global::System.Single cena, global::System.Boolean nakup, global::System.DateTime datum_zmeny)
        {
            portfolio portfolio = new portfolio();
            portfolio.portfolio_id = portfolio_id;
            portfolio.uzivatel_id = uzivatel_id;
            portfolio.akcie_id = akcie_id;
            portfolio.pocet = pocet;
            portfolio.cena = cena;
            portfolio.nakup = nakup;
            portfolio.datum_zmeny = datum_zmeny;
            return portfolio;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 portfolio_id
        {
            get
            {
                return _portfolio_id;
            }
            set
            {
                if (_portfolio_id != value)
                {
                    Onportfolio_idChanging(value);
                    ReportPropertyChanging("portfolio_id");
                    _portfolio_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("portfolio_id");
                    Onportfolio_idChanged();
                }
            }
        }
        private global::System.Int32 _portfolio_id;
        partial void Onportfolio_idChanging(global::System.Int32 value);
        partial void Onportfolio_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 uzivatel_id
        {
            get
            {
                return _uzivatel_id;
            }
            set
            {
                Onuzivatel_idChanging(value);
                ReportPropertyChanging("uzivatel_id");
                _uzivatel_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uzivatel_id");
                Onuzivatel_idChanged();
            }
        }
        private global::System.Int32 _uzivatel_id;
        partial void Onuzivatel_idChanging(global::System.Int32 value);
        partial void Onuzivatel_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 akcie_id
        {
            get
            {
                return _akcie_id;
            }
            set
            {
                Onakcie_idChanging(value);
                ReportPropertyChanging("akcie_id");
                _akcie_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("akcie_id");
                Onakcie_idChanged();
            }
        }
        private global::System.Int32 _akcie_id;
        partial void Onakcie_idChanging(global::System.Int32 value);
        partial void Onakcie_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pocet
        {
            get
            {
                return _pocet;
            }
            set
            {
                OnpocetChanging(value);
                ReportPropertyChanging("pocet");
                _pocet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pocet");
                OnpocetChanged();
            }
        }
        private global::System.Int32 _pocet;
        partial void OnpocetChanging(global::System.Int32 value);
        partial void OnpocetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single cena
        {
            get
            {
                return _cena;
            }
            set
            {
                OncenaChanging(value);
                ReportPropertyChanging("cena");
                _cena = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cena");
                OncenaChanged();
            }
        }
        private global::System.Single _cena;
        partial void OncenaChanging(global::System.Single value);
        partial void OncenaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean nakup
        {
            get
            {
                return _nakup;
            }
            set
            {
                OnnakupChanging(value);
                ReportPropertyChanging("nakup");
                _nakup = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nakup");
                OnnakupChanged();
            }
        }
        private global::System.Boolean _nakup;
        partial void OnnakupChanging(global::System.Boolean value);
        partial void OnnakupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime datum_zmeny
        {
            get
            {
                return _datum_zmeny;
            }
            set
            {
                Ondatum_zmenyChanging(value);
                ReportPropertyChanging("datum_zmeny");
                _datum_zmeny = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datum_zmeny");
                Ondatum_zmenyChanged();
            }
        }
        private global::System.DateTime _datum_zmeny;
        partial void Ondatum_zmenyChanging(global::System.DateTime value);
        partial void Ondatum_zmenyChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_portfolio_akcie", "akcie")]
        public akcie akcie
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akcie>("dbModel.FK_portfolio_akcie", "akcie").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akcie>("dbModel.FK_portfolio_akcie", "akcie").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<akcie> akcieReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akcie>("dbModel.FK_portfolio_akcie", "akcie");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<akcie>("dbModel.FK_portfolio_akcie", "akcie", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_portfolio_uzivatel", "uzivatel")]
        public uzivatel uzivatel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<uzivatel>("dbModel.FK_portfolio_uzivatel", "uzivatel").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<uzivatel>("dbModel.FK_portfolio_uzivatel", "uzivatel").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<uzivatel> uzivatelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<uzivatel>("dbModel.FK_portfolio_uzivatel", "uzivatel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<uzivatel>("dbModel.FK_portfolio_uzivatel", "uzivatel", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="sledovane")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sledovane : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sledovane object.
        /// </summary>
        /// <param name="sledovane_id">Initial value of the sledovane_id property.</param>
        /// <param name="nazev">Initial value of the nazev property.</param>
        /// <param name="uzivatel_id">Initial value of the uzivatel_id property.</param>
        /// <param name="akcie_id">Initial value of the akcie_id property.</param>
        public static sledovane Createsledovane(global::System.Int32 sledovane_id, global::System.String nazev, global::System.Int32 uzivatel_id, global::System.Int32 akcie_id)
        {
            sledovane sledovane = new sledovane();
            sledovane.sledovane_id = sledovane_id;
            sledovane.nazev = nazev;
            sledovane.uzivatel_id = uzivatel_id;
            sledovane.akcie_id = akcie_id;
            return sledovane;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sledovane_id
        {
            get
            {
                return _sledovane_id;
            }
            set
            {
                if (_sledovane_id != value)
                {
                    Onsledovane_idChanging(value);
                    ReportPropertyChanging("sledovane_id");
                    _sledovane_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sledovane_id");
                    Onsledovane_idChanged();
                }
            }
        }
        private global::System.Int32 _sledovane_id;
        partial void Onsledovane_idChanging(global::System.Int32 value);
        partial void Onsledovane_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nazev
        {
            get
            {
                return _nazev;
            }
            set
            {
                OnnazevChanging(value);
                ReportPropertyChanging("nazev");
                _nazev = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nazev");
                OnnazevChanged();
            }
        }
        private global::System.String _nazev;
        partial void OnnazevChanging(global::System.String value);
        partial void OnnazevChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 uzivatel_id
        {
            get
            {
                return _uzivatel_id;
            }
            set
            {
                Onuzivatel_idChanging(value);
                ReportPropertyChanging("uzivatel_id");
                _uzivatel_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uzivatel_id");
                Onuzivatel_idChanged();
            }
        }
        private global::System.Int32 _uzivatel_id;
        partial void Onuzivatel_idChanging(global::System.Int32 value);
        partial void Onuzivatel_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 akcie_id
        {
            get
            {
                return _akcie_id;
            }
            set
            {
                Onakcie_idChanging(value);
                ReportPropertyChanging("akcie_id");
                _akcie_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("akcie_id");
                Onakcie_idChanged();
            }
        }
        private global::System.Int32 _akcie_id;
        partial void Onakcie_idChanging(global::System.Int32 value);
        partial void Onakcie_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_sledovane_akcie", "akcie")]
        public akcie akcie
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akcie>("dbModel.FK_sledovane_akcie", "akcie").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akcie>("dbModel.FK_sledovane_akcie", "akcie").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<akcie> akcieReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akcie>("dbModel.FK_sledovane_akcie", "akcie");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<akcie>("dbModel.FK_sledovane_akcie", "akcie", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_sledovane_uzivatel", "uzivatel")]
        public uzivatel uzivatel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<uzivatel>("dbModel.FK_sledovane_uzivatel", "uzivatel").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<uzivatel>("dbModel.FK_sledovane_uzivatel", "uzivatel").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<uzivatel> uzivatelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<uzivatel>("dbModel.FK_sledovane_uzivatel", "uzivatel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<uzivatel>("dbModel.FK_sledovane_uzivatel", "uzivatel", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="uzivatel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class uzivatel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new uzivatel object.
        /// </summary>
        /// <param name="uzivatel_id">Initial value of the uzivatel_id property.</param>
        /// <param name="jmeno">Initial value of the jmeno property.</param>
        /// <param name="prijmeni">Initial value of the prijmeni property.</param>
        /// <param name="adresa_id">Initial value of the adresa_id property.</param>
        public static uzivatel Createuzivatel(global::System.Int32 uzivatel_id, global::System.String jmeno, global::System.String prijmeni, global::System.Int32 adresa_id)
        {
            uzivatel uzivatel = new uzivatel();
            uzivatel.uzivatel_id = uzivatel_id;
            uzivatel.jmeno = jmeno;
            uzivatel.prijmeni = prijmeni;
            uzivatel.adresa_id = adresa_id;
            return uzivatel;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 uzivatel_id
        {
            get
            {
                return _uzivatel_id;
            }
            set
            {
                if (_uzivatel_id != value)
                {
                    Onuzivatel_idChanging(value);
                    ReportPropertyChanging("uzivatel_id");
                    _uzivatel_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uzivatel_id");
                    Onuzivatel_idChanged();
                }
            }
        }
        private global::System.Int32 _uzivatel_id;
        partial void Onuzivatel_idChanging(global::System.Int32 value);
        partial void Onuzivatel_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String jmeno
        {
            get
            {
                return _jmeno;
            }
            set
            {
                OnjmenoChanging(value);
                ReportPropertyChanging("jmeno");
                _jmeno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("jmeno");
                OnjmenoChanged();
            }
        }
        private global::System.String _jmeno;
        partial void OnjmenoChanging(global::System.String value);
        partial void OnjmenoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prijmeni
        {
            get
            {
                return _prijmeni;
            }
            set
            {
                OnprijmeniChanging(value);
                ReportPropertyChanging("prijmeni");
                _prijmeni = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("prijmeni");
                OnprijmeniChanged();
            }
        }
        private global::System.String _prijmeni;
        partial void OnprijmeniChanging(global::System.String value);
        partial void OnprijmeniChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 adresa_id
        {
            get
            {
                return _adresa_id;
            }
            set
            {
                Onadresa_idChanging(value);
                ReportPropertyChanging("adresa_id");
                _adresa_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("adresa_id");
                Onadresa_idChanged();
            }
        }
        private global::System.Int32 _adresa_id;
        partial void Onadresa_idChanging(global::System.Int32 value);
        partial void Onadresa_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String poznamka
        {
            get
            {
                return _poznamka;
            }
            set
            {
                OnpoznamkaChanging(value);
                ReportPropertyChanging("poznamka");
                _poznamka = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("poznamka");
                OnpoznamkaChanged();
            }
        }
        private global::System.String _poznamka;
        partial void OnpoznamkaChanging(global::System.String value);
        partial void OnpoznamkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> penezenka
        {
            get
            {
                return _penezenka;
            }
            set
            {
                OnpenezenkaChanging(value);
                ReportPropertyChanging("penezenka");
                _penezenka = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("penezenka");
                OnpenezenkaChanged();
            }
        }
        private Nullable<global::System.Single> _penezenka;
        partial void OnpenezenkaChanging(Nullable<global::System.Single> value);
        partial void OnpenezenkaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_uzivatel_adresa", "adresa")]
        public adresa adresa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<adresa>("dbModel.FK_uzivatel_adresa", "adresa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<adresa>("dbModel.FK_uzivatel_adresa", "adresa").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<adresa> adresaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<adresa>("dbModel.FK_uzivatel_adresa", "adresa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<adresa>("dbModel.FK_uzivatel_adresa", "adresa", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_portfolio_uzivatel", "portfolio")]
        public EntityCollection<portfolio> portfolio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<portfolio>("dbModel.FK_portfolio_uzivatel", "portfolio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<portfolio>("dbModel.FK_portfolio_uzivatel", "portfolio", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_sledovane_uzivatel", "sledovane")]
        public EntityCollection<sledovane> sledovane
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<sledovane>("dbModel.FK_sledovane_uzivatel", "sledovane");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<sledovane>("dbModel.FK_sledovane_uzivatel", "sledovane", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
